Update watches-support & some edits
AsteroidOS/asteroidos.org pull request #188
Opened 2022-09-22 13:12 UTC by docgalaxyblock

I have resort the [watches-support.json](https://github.com/docgalaxyblock/asteroidos.org/blob/update-features/pages/watches-support.json) to one straight order.

Add file [all-features-template.json](https://github.com/docgalaxyblock/asteroidos.org/blob/update-features/pages/all-features-template.json) that acts as a template for new watches and is an overview of all features we currently have or are in development

2022-09-22 19:35 UTC, docgalaxyblock commented
Hey @locusf do you still have an `anthias`?
If you still have it could you please check if `tilt-to-wake` works
and I read today that it has a hearth reate sensor too - I guess since the time you worked on the port it was not working?

2022-09-27 14:21 UTC, locusf commented
I do have it but I'm missing the cradle to get it charged and updated.

2022-10-02 11:36 UTC, FlorentRevest commented
I realize this is still a draft but this PR is really quite confusing at the moment. For example:

-  "Update harmony.md" doesn't help because it's pretty clear from reading the commit that you update that file, you should rather explain what you did and why (eg: uniformize capital letter usage)
- "resort watch features" it's not clear at all to me why all these lines are getting re-ordered and what the benefit is. you should explain why this matters. There are also a bunch of "####################" which don't seem to make sense to me either
- a commit titled "fix" which adds a comment in german shouldn't make it to a PR https://github.com/AsteroidOS/asteroidos.org/pull/188/commits/f02b22d260349feb2e9402ec0548c228b617202e
- In "Create all-features-template.json" could you also explain what is this template and why it's good ? Is this a standard practice to have a template.json somewhere ? It sounds like what you want to achieve is close to a "schema" https://json-schema.org/learn/getting-started-step-by-step which could automate validation of our json file but I don't see what this template file really achieves
- In "Update watches-support & some edits" I see more "////////////////////" and edits which should break the json file (like free form "46mm" out of any property) the code should stay bisectable https://andrealmeid.com/post/2022-07-31-keep-bisect/ 
- In "Update watches-support & some edits" you rename a "name" property into "..." I also don't understand what you're trying to achieve there.
- At this point I stopped reviewing because I just don't get what you're trying to achieve

You can refer to https://cbea.ms/git-commit/ for good commit guidance, this would greatly help the reviewer. You can refer to https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history for history rewrite guidance.

@beroset you have more context on the watches features json, could you have a look once @docgalaxyblock has addressed the above ?

2022-10-02 13:19 UTC, docgalaxyblock commented
@FlorentRevest I apologize
git is new to me and I only used the github webeditor. That is how I got to this commit mess ...
It guess it is probably easier to take a look at the `Files changed` Tab instead of the `Commits` one

`Update xxx.md` is the default that github provides if you forget to provide one.

My bunch of `/` (or `#`  before) are lines where I am awaiting response how the current state is
At thirst I have marked my edited lines by a bunch of `#`

> To your points 3-5:

I have asked @beroset on matrix how I can add comments to the json without breaking the interpreter.
The solution is to use propertys that are not referenced anywhere

*My intention was to have hardware feature notes at the json that are not displayed on site cause things like Celluar have no software support but the hardware is there. Also this does not clutter the feature tables if you are on mobile.*



I will deploy my own git server to get used to git while waiting for the responses.

2022-10-16 23:00 UTC, beroset commented
If you could 1) rebase this on `master` and 2) eliminate [bbd3638](https://github.com/AsteroidOS/asteroidos.org/pull/188/commits/bbd3638cd91f1f5a646f8a364ae6c47435f3eff5) and [40c8133](https://github.com/AsteroidOS/asteroidos.org/pull/188/commits/40c813375f848548e0b58e9279c2a72cd8a5902b), this is a good fix.

2022-10-17 11:46 UTC, beroset requested changes
Only needs a minor change in `all-features-template.json`

2022-10-17 11:46 UTC, beroset commented on pages/all-features-template.json
> +        { "name":"Steps", "status":"bad" },                                     // not yet implemented anywhere
Although this isn't actually interpreted by anything, better would be to use the `comment` tag to show how it should be done.

2022-10-17 11:46 UTC, beroset commented on pages/watches-support.json
> -      "status":"supported",
Good catch!

2022-10-28 20:23 UTC, MagneFire reviewed
Thank you for this PR! It's great to see the consistency issues fixed!
Generally this PR looks good.

I would suggest you to change the "Ambient Light" to "Light sensor" as that's a bit more descriptive. Ideally it would be "Ambient light sensor" but that too long.

Most of my comments are related to the support state of a specific watch feature, I'd be fine if you wouldn't change them in this PR as it's a bit out of scope.

2022-10-28 20:23 UTC, MagneFire commented on pages/watches-support.json
> +        { "name":"Microphone", "status":"bad" },
The microphone is actually functional on `swift`: https://github.com/AsteroidOS/meta-swift-hybris/pull/9

2022-10-28 20:23 UTC, MagneFire commented on pages/watches-support.json
> +        { "name":"Speaker", "status":"unknown" },
The speaker doesn't work yet on `catfish`. That's future talk: https://github.com/AsteroidOS/meta-smartwatch/pull/109

2022-10-28 20:23 UTC, MagneFire commented on pages/watches-support.json
> +        { "name":"Compass", "status":"bad" },
`wren` doesn't have a compass.

2022-10-28 20:23 UTC, MagneFire commented on pages/watches-support.json
> +        { "name":"Compass", "status":"bad" },
`swift` doesn't have a compass

2022-10-28 20:47 UTC, docgalaxyblock commented on pages/watches-support.json
>          { "name":"Display", "status":"good" },
how about `partly`?

2022-10-28 20:50 UTC, docgalaxyblock commented on pages/watches-support.json
> +        { "name":"Cellular", "status":"bad", "comment": "46mm only" }
This not is not referenced anywhere, It is only a devnote
"one variant of the 64mm only"?

2022-10-28 20:50 UTC, MagneFire commented on pages/watches-support.json
>          { "name":"Display", "status":"good" },
It only ever shows the AsteroidOS boot logo, nothing else due to some missing system files. It's been like this for some time now, which is why I tend to lean towards `bad`, but `partly` could work well. But might give the impression that it's fixed 'soon'.

2022-10-28 20:52 UTC, docgalaxyblock commented on pages/watches-support.json
> +        { "name":"Cellular", "status":"bad" }
yup - seems like I forgot the devnote or thought since cellular is not planned in the near future that the note has no benefit

2022-10-28 21:10 UTC, dodoradio commented on pages/watches-support.json
> +        { "name":"Cellular", "status":"bad" }
Both cat and saw `fish` variants lack esim, both `shark` have 4g - in the case of sawshark it's a physical sim, in the case of catshark is an esim

2022-10-28 21:14 UTC, MagneFire commented on pages/watches-support.json
> +        { "name":"Cellular", "status":"bad" }
> yup - seems like I forgot the devnote on `sawshark` It seems like you mixed up `cat-/sawshark?`

Ah, yes. I was obviously talking about `sawshark` not `catshark`. Sorry about that...

2022-10-28 21:20 UTC, beroset commented on pages/watches-support.json
> +        { "name":"Cellular", "status":"bad" }
*whew!* We're going to need footnotes on the status table soon.  ;)  Seriously, though, good job to all for cleaning this up and clarifying.

2022-10-29 09:57 UTC, FlorentRevest commented
Seriously great work, thanks for the time spent looking into all of this! :) 

I see that in a few cases you added a "comment" field, it got me thinking, why not use it as a tooltip when the user hovers their mouse over the specific support table cell ? :) it would be good context to surface to the user.

2022-10-29 11:13 UTC, docgalaxyblock commented
Thanks

> I see that in a few cases you added a "comment" field, it got me thinking, why not use it as a tooltip when the user hovers their mouse over the specific support table cell ? :) it would be good context to surface to the user.

@beroset You have the job 😉

2022-10-29 11:52 UTC, beroset approved these changes
Great work!

2022-10-29 12:06 UTC, docgalaxyblock commented
I think that was the last force-push, I hope that everything is fixed now
A month part-time/weekend work...
Merge it 😀

2022-10-29 12:19 UTC, merged

2022-10-29 12:20 UTC, FlorentRevest commented
Thank you for the time you spent on this @docgalaxyblock !