Added Alpine Linux package list
AsteroidOS/asteroidos.org pull request #361
Opened 2023-04-30 22:51 UTC by maalos

Capitalize "Linux" in the note if necessary.

2023-04-30 22:59 UTC, eLtMosen requested changes
As noted on matrix, the Linux reads a bit awkward as lowercase linux :sweat_smile: 

Thank you very much for your work on this!
Very much appreciated.

2023-04-30 23:03 UTC, eLtMosen approved these changes

2023-04-30 23:03 UTC, eLtMosen commented
Thanks for the swift action!

2023-04-30 23:06 UTC, merged

2023-05-03 22:27 UTC, FlorentRevest commented on pages/wiki/building-asteroidos.md
> +| Alpine | ```apk add binutils chrpath gcc g++ gawk gcc lz4 make patch perl rpcgen``` <br>Note: Alpine Linux does not contain diffstat in it's repositories, thus you have to [build it yourself from s
its* :)